header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Canonical Ltd.
    content: |
      Copyright [year] [owner]
      See LICENSE file for licensing details.
    # License year is supposed to be the year where a file is first created.
    # But the workflow does not check it correctly, so we change the pattern.
    pattern: |
      Copyright \d{4} Canonical Ltd.
      See LICENSE file for licensing details.
  paths:
    - '**'
  paths-ignore:
    - '.github/**'
    - '**/.gitkeep'
    - '**/*.cfg'
    - '**/*.conf'
    - '**/*.j2'
    - '**/*.json'
    - '**/*.md'
    - '**/*.rule'
    - '**/*.tmpl'
    - '**/*.txt'
    - '**/*.jinja'
    - '.codespellignore'
    - '.dockerignore'
    - '.flake8'
    - '.jujuignore'
    - '.gitignore'
    - '.licenserc.yaml'
    - '.trivyignore'
    - '.woke.yaml'
    - '.woke.yml'
    - 'CODEOWNERS'
    - 'icon.svg'
    - 'LICENSE'
    - 'trivy.yaml'
    - 'lib/**'
    - 'templates/*'
    - 'uv.lock'
    - 'superset_rock/startup-scripts/**'
    - 'superset_rock/patches/41001-fix-detached-instance-error.patch'
  comment: on-failure
