ignore_files:
  # Ignore charm libraries as they use non compliant terminology.
  - lib/charms/redis_k8s/v0/redis.py
rules:
  # Ignore "master" - the database relation event received from the library.
  - name: master
