# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

# This file defines charm config options, and populates the Configure tab on Charmhub.
# If your charm does not require configuration options, delete this file entirely.
#
# See https://juju.is/docs/config for guidance.

options:
  allow-image-domains: 
    description: |
        Comma separated list of domains from which to allow images according to the CSP.
    type: string
  external-hostname:
    description: |
        The DNS listing used for external connections. 
        Will default to the name of the deployed application.
    type: string
    default: superset-k8s
  tls-secret-name:
    description: |
        Name of the k8s secret which contains the TLS certificate to be used by ingress.
    default: superset-tls
    type: string
  superset-secret-key:
    description: |
        Your App secret key will be used for securely signing the session cookie
        and encrypting sensitive information on the database. If not defined a secret
        will be automatically generated.
    type: string
  admin-password:
    description: |
        The secret for the admin account created on app initialisation. Default is 'admin'.
    default: admin
    type: string
  charm-function:
    description: |
        The type of superset function you want the charm to fulfill.
        Allowed options are: 'app-gunicorn', 'app', 'worker', 'beat'
    default: app-gunicorn
    type: string
  sqlalchemy-pool-size:
    description: |
        Specifies the maximum number of database connections
        that can be kept in the connection pool.
    default: 5
    type: int
  sqlalchemy-pool-timeout:
    description: |
        Defines the maximum time (in seconds) a thread is allowed
        to wait for a connection from the pool.
    default: 300
    type: int
  sqlalchemy-max-overflow:
    description: |
        Sets the maximum number of connections that can be created
        beyond the pool size when the pool is exhausted.
    default: 5
    type: int
  google-client-id:
    description: |
      Client id from Google Oauth setup
    type: string
  google-client-secret:
    description: |
      Client password from Google Oauth setup
    type: string
  oauth-domain:
    description: |
      The domain for which to allow Google authentication i.e. canonical.com
    type: string
  oauth-admin-email:
    description: |
      Email(s) to be given an Admin role on initialization.
      Either a single email or a comma separated list.
      eg. "example.email@company.com, example.email2@company.com"
    type: string
    default: admin@superset.com
  self-registration-role:
    description: |
      The default role to be provided to users that self-register via Oauth.
      This role must exist already in Superset and is case sensitive.
    type: string
    default: Public
  http-proxy:
    description: |
      The HTTP_PROXY value.
    type: string
  https-proxy:
    description: |
      The HTTPS_PROXY value.
    type: string
  no-proxy:
    description: |
      A comma-separated list of host names that should not go through any proxy.
    type: string
  load-examples:
    description: |
      Loads example data source with corresponding data sets and charts for testing.
    type: boolean
    default: False
  html-sanitization:
    description: |
      Sanitizes the HTML content used in markdowns to allow its rendering in a safe manner.
      Disabling this option is not recommended for security reasons
    type: boolean
    default: True
  html-sanitization-schema-extensions:
    description: |
      Use this configuration to extend the HTML sanitization schema.
    type: string
  feature-flags:
    description: |
       A comma-separated list of feature defined in https://github.com/apache/superset/blob/HEAD/RESOURCES/FEATURE_FLAGS.md.
       To disable features enabled by default, precede them with a ! symbol. E.g: ENABLED_FEATURE,!DISABLED_FEATURE.
    type: string
  global-async-queries-jwt:
    description: |
      jwt for communication with redis database for async querying
    type: string
    default: "18b2f8fcd0d708d270c00508da6e8dfc7a21eff14ea438056809805150439a04"
  global-async-queries-polling-delay:
    description: |
      The timedelay in milliseconds for polling during asynchronous query execution.
    type: int
    default: 500
  sentry-dsn:
    description: |
      The unique key for the Sentry project in which to log exceptions.
    type: string
  sentry-environment:
    description: |
      The environment to log errors to in Sentry.
    type: string
  sentry-release:
    description: |
      The version of code deployed to an environment.
    type: string
  sentry-sample-rate:
    description: |
      A number between 0 and 1 representing what % of errors should be sent to Sentry.
      ie for 0.25, 25% of errors will be sent to Sentry.
    default: "1"
    type: string
  sentry-redact-params:
    description: Indicates whether or not event parameters sent to Sentry should be redacted.
    default: false
    type: boolean
  server-alias:
    description: The alias the server charm has been deployed with if it differs from the default.
    default: superset-k8s
    type: string
  webserver-timeout:
    description: The time in seconds the server can maintain a database connection.
    default: 180
    type: int
  cache-warmup:
    description: Boolean representing if the cache warm-up functionality should be enabled.
    default: False
    type: boolean
  redis-timeout:
    description: The time in seconds cached data will remain valid in Redis.
    default: 300
    type: int
  smtp-secret-id:
    description: ID of the Juju secret for the SMTP credentials used to send emails.
    type: string
  dashboard-size-limit:
    description: Integer representing how many characters to allow in a dashboard definition.
    default: 65535
    type: int
