# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

[tox]
skipsdist = True
skip_missing_interpreters = True
envlist = fmt, lint, unit, static, coverage-report
max-line-length=120

[vars]
src_path = {toxinidir}/src/
tst_path = {toxinidir}/tests/
all_path = {[vars]src_path} {[vars]tst_path}
uv_flags = --frozen --isolated --extra=dev

[testenv]
allowlist_externals = uv
basepython = python3
setenv =
  PYTHONPATH = {toxinidir}:{toxinidir}/lib:{[vars]src_path}
  PYTHONBREAKPOINT=ipdb.set_trace
  PY_COLORS=1
passenv =
  PYTHONPATH
  CHARM_BUILD_DIR
  MODEL_SETTINGS

[testenv:lock]
description = Update uv.lock with the latest deps
commands =
  uv lock --upgrade --no-cache

[testenv:fmt]
description = Format the code
commands =
  uv run {[vars]uv_flags} isort {[vars]src_path} {[vars]tst_path}
  uv run {[vars]uv_flags} black {[vars]src_path} {[vars]tst_path}

[testenv:lint]
description = Lint the code
commands =
  uv run {[vars]uv_flags} pydocstyle {[vars]src_path}
  uv run {[vars]uv_flags} codespell {toxinidir} --skip {toxinidir}/.git --skip {toxinidir}/.tox --ignore-words-list "ro" \
      --skip {toxinidir}/build --skip {toxinidir}/lib --skip {toxinidir}/venv \
      --skip {toxinidir}/.mypy_cache --skip {toxinidir}/icon.svg --skip uv.lock
  uv run {[vars]uv_flags} pflake8 {[vars]src_path} {[vars]tst_path}
  uv run {[vars]uv_flags} isort --check-only --diff {[vars]src_path} {[vars]tst_path}
  uv run {[vars]uv_flags} black --line-length 79 --check --diff {[vars]src_path} {[vars]tst_path}
  uv run {[vars]uv_flags} mypy {[vars]all_path} --ignore-missing-imports --follow-imports=skip --install-types --non-interactive
  uv run {[vars]uv_flags} pylint {[vars]all_path} --disable=E0401,W1203,W0613,W0718,R0903,W1514,C0103,R0913,C0301,W0212,R0902,C0104,R0201,E1121,R0801,E1120

[testenv:unit]
description = Run unit tests
commands =
  uv run {[vars]uv_flags} coverage run --source={[vars]src_path} \
      -m pytest --ignore={[vars]tst_path}integration -v --tb native -s {posargs}
  uv run {[vars]uv_flags} coverage report

[testenv:static]
description = Run static analysis tests
commands =
  uv run {[vars]uv_flags} bandit -c {toxinidir}/pyproject.toml -r {[vars]src_path} {[vars]tst_path}

[testenv:coverage-report]
description = Create test coverage report
commands =
  uv run {[vars]uv_flags} coverage report

[testenv:integration]
description = Run integration tests
commands =
  uv run {[vars]uv_flags} pytest {[vars]tst_path}integration -v --tb native --ignore={[vars]tst_path}unit --log-cli-level=INFO -s {posargs}

[testenv:integration-charm]
description = Run integration tests
commands =
  uv run {[vars]uv_flags} pytest {[vars]tst_path}integration/test_charm.py -v --tb native --ignore={[vars]tst_path}unit --log-cli-level=INFO -s {posargs}

[testenv:integration-upgrades]
description = Run integration tests
commands =
  uv run {[vars]uv_flags} pytest {[vars]tst_path}integration/test_upgrades.py -v --tb native --ignore={[vars]tst_path}unit --log-cli-level=INFO -s {posargs}

[testenv:integration-scaling]
description = Run integration tests
commands =
  uv run {[vars]uv_flags} pytest {[vars]tst_path}integration/test_scaling.py -v --tb native --ignore={[vars]tst_path}unit --log-cli-level=INFO -s {posargs}

[testenv:integration-trino-catalog]
description = Run Trino catalog integration tests
commands =
  uv run {[vars]uv_flags} pytest {[vars]tst_path}integration/test_trino_catalog.py -v --tb native --ignore={[vars]tst_path}unit --log-cli-level=INFO -s {posargs}
