# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

#!/usr/bin/env python3
"""
Grant a Superset user (e.g. gamma_user) owner access to dashboards.

Gamma is restricted by default: a Gamma user only sees dashboards/charts that have
been explicitly shared with them. test-mcp-auth.py's fixture setup intentionally does
NOT grant gamma_user any dashboard access — that restriction is the thing test #6 in
the suite is checking for. This script closes that gap when you actually want
gamma_user to see something (e.g. driving the MCP client through an opencode.json
generated by generate-mcp-config.py).

Usage:
    # grant access to every existing dashboard
    python3 grant-dashboard-access.py gamma_user --superset-url http://10.223.71.200:30188

    # grant access to specific dashboards only
    python3 grant-dashboard-access.py gamma_user --dashboard "USA Births Names" \\
        --superset-url http://10.223.71.200:30188

Prerequisites:
    Superset admin credentials (defaults: admin / admin123)
"""

import argparse
import http.cookiejar
import json
import re
import sys
import urllib.error
import urllib.parse
import urllib.request

SUPERSET_ADMIN_USER = "admin"


def api(method: str, url: str, body=None, headers: dict | None = None) -> tuple[int, dict]:
    data = json.dumps(body).encode() if body is not None else None
    h = {"Content-Type": "application/json", "Accept": "application/json"}
    if headers:
        h.update(headers)
    req = urllib.request.Request(url, data=data, headers=h, method=method)
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            return resp.status, json.loads(resp.read())
    except urllib.error.HTTPError as e:
        try:
            return e.code, json.loads(e.read())
        except Exception:
            return e.code, {}


def session_api(opener, method: str, url: str, body=None,
                extra_headers: dict | None = None) -> tuple[int, dict]:
    data = json.dumps(body).encode() if body is not None else None
    h = {"Content-Type": "application/json", "Accept": "application/json"}
    if extra_headers:
        h.update(extra_headers)
    req = urllib.request.Request(url, data=data, headers=h, method=method)
    try:
        with opener.open(req, timeout=15) as resp:
            return resp.status, json.loads(resp.read())
    except urllib.error.HTTPError as e:
        try:
            return e.code, json.loads(e.read())
        except Exception:
            return e.code, {}


def superset_login(base: str, password: str) -> tuple[str, str, urllib.request.OpenerDirector]:
    _, d = api("POST", f"{base}/api/v1/security/login",
               {"username": SUPERSET_ADMIN_USER, "password": password, "provider": "db"})
    api_token = d.get("access_token")
    if not api_token:
        sys.exit(f"[ERROR] Superset login failed: {d}")

    jar = http.cookiejar.CookieJar()
    opener = urllib.request.build_opener(urllib.request.HTTPCookieProcessor(jar))

    resp = opener.open(f"{base}/login/")
    html = resp.read().decode()
    m = re.search(r'name=["\']csrf_token["\'][^>]*value=["\']([^"\']+)["\']', html) or \
        re.search(r'value=["\']([^"\']+)["\'][^>]*name=["\']csrf_token["\']', html)
    form_csrf = m.group(1) if m else ""

    form_data = urllib.parse.urlencode({
        "username": SUPERSET_ADMIN_USER,
        "password": password,
        "csrf_token": form_csrf,
    }).encode()
    opener.open(f"{base}/login/", form_data)

    req = urllib.request.Request(
        f"{base}/api/v1/security/csrf_token/",
        headers={"Authorization": f"Bearer {api_token}"},
    )
    with opener.open(req) as resp:
        csrf_token = json.loads(resp.read()).get("result", "")

    return api_token, csrf_token, opener


def get_user_id(base: str, api_token: str, username: str) -> int:
    _, d = api("GET", f"{base}/api/v1/security/users/?q=(page_size:100)",
               headers={"Authorization": f"Bearer {api_token}"})
    for u in d.get("result", []):
        if u["username"] == username:
            return u["id"]
    sys.exit(f"[ERROR] User '{username}' not found. Run test-mcp-auth.py first to create fixtures.")


def list_dashboards(base: str, api_token: str) -> list[dict]:
    _, d = api("GET", f"{base}/api/v1/dashboard/?q=(page_size:100)",
               headers={"Authorization": f"Bearer {api_token}"})
    return d.get("result", [])


def grant_owner(base: str, opener, api_token: str, csrf_token: str, dashboard: dict, user_id: int) -> None:
    dash_id = dashboard["id"]
    existing_owner_ids = [o["id"] for o in dashboard.get("owners", [])]
    if user_id in existing_owner_ids:
        print(f"    '{dashboard['dashboard_title']}' (id={dash_id}) already shared")
        return
    status, d = session_api(opener, "PUT", f"{base}/api/v1/dashboard/{dash_id}",
                            {"owners": existing_owner_ids + [user_id]},
                            extra_headers={
                                "Authorization": f"Bearer {api_token}",
                                "X-CSRFToken": csrf_token,
                                "Referer": base,
                            })
    if status not in (200, 201):
        print(f"    [FAIL] '{dashboard['dashboard_title']}' (id={dash_id}): {status} {d}")
        return
    print(f"    granted: '{dashboard['dashboard_title']}' (id={dash_id})")


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("user", help="Superset username to grant dashboard access to, e.g. gamma_user")
    parser.add_argument("--dashboard", action="append", dest="dashboards",
                        help="Dashboard title to grant (repeatable). Default: all dashboards.")
    parser.add_argument("--superset-url", default="http://10.223.71.200:30088")
    parser.add_argument("--superset-password", default="admin123")
    args = parser.parse_args()

    api_token, csrf_token, opener = superset_login(args.superset_url, args.superset_password)
    user_id = get_user_id(args.superset_url, api_token, args.user)

    dashboards = list_dashboards(args.superset_url, api_token)
    if args.dashboards:
        wanted = set(args.dashboards)
        dashboards = [d for d in dashboards if d["dashboard_title"] in wanted]
        missing = wanted - {d["dashboard_title"] for d in dashboards}
        if missing:
            sys.exit(f"[ERROR] Dashboard(s) not found: {sorted(missing)}")
    if not dashboards:
        sys.exit("[ERROR] No dashboards found on this instance.")

    print(f"Granting '{args.user}' (id={user_id}) owner access to {len(dashboards)} dashboard(s):")
    for dash in dashboards:
        grant_owner(args.superset_url, opener, api_token, csrf_token, dash, user_id)


if __name__ == "__main__":
    main()
