name: Integration tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  workflow_call:

jobs:
  integration-tests:
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    secrets: inherit
    permissions:
      contents: read
      packages: write
    with:
      test-timeout: 90
      provider: "k8s"
      channel: "1.32-classic/stable"
      use-canonical-k8s: true
      upload-image: "artifact"
      pre-run-script: .github/scripts/setup-artifact-import.sh
      extra-arguments: |
        --kube-config=~/.kube/config
      juju-channel: "3/stable"
      self-hosted-runner: false
      trivy-severity-config: CRITICAL
      modules: >-
        ["test_deployment.py",
        "test_lifecycle.py",
        "test_scaling.py",
        "test_relation_order.py",
        "test_upgrades.py",
        "test_oauth.py",
        "test_smtp.py",
        "test_reports.py",
        "test_trino_catalog.py",
        "test_observability.py"]
      with-uv: true
