name: Integration tests
on:
  pull_request:
  workflow_call:
jobs:
  integration-test-microk8s:
    name: Integration tests (microk8s)
    strategy:
      fail-fast: false
      matrix:
        tox-environments:
          - integration-charm
          - integration-upgrades
          - integration-scaling
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          juju-channel: 3.4/stable
          provider: microk8s
          microk8s-addons:  "dns ingress rbac storage metallb:10.15.119.2-10.15.119.4 registry"
          channel: 1.28-strict/stable
      - name: Run integration tests
        run: tox -e ${{ matrix.tox-environments }}
