name: Integration tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  workflow_call:

jobs:
  integration-tests:
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    secrets: inherit
    with:
      channel: 1.28-strict/stable
      modules: '["test_charm.py", "test_scaling.py", "test_upgrades.py"]'
      juju-channel: 3.4/stable
      self-hosted-runner: false
      microk8s-addons: "dns ingress rbac storage metallb:10.15.119.2-10.15.119.4 registry"
      trivy-severity-config: CRITICAL
      trivy-image-config: .github/trivy.yaml