name: Promote charm

on:
  workflow_dispatch:
    inputs:
      origin-channel:
        description: 'Origin Channel e.g. latest/edge'
        required: true
      destination-channel:
        description: 'Destination Channel e.g. 6/beta'
        required: true

jobs:
  promote-charm:
    uses: canonical/operator-workflows/.github/workflows/promote_charm.yaml@main
    with:
      origin-channel: ${{ github.event.inputs.origin-channel }}
      destination-channel: ${{ github.event.inputs.destination-channel }}
    secrets:
      CHARMHUB_TOKEN: ${{ secrets.CHARMHUB_TOKEN }}
